### PR TITLE
Shorten articles with js and css

### PR DESCRIPTION
**Pull request by mdoff**
If post is longer than 450px then is cropped with css, can be extended by clicking on 'Show all'.

### CODE REVIEW

**Comment by rozie** [comment]
After not so short hesitation (adding complexity, adding JS requirement, fixes only visible part - all data are loaded anyway), I tried to run with this template and test it.
1. It shows full body on non-JS browser (good), but adds invalid URLs with "show all" anchor text (bad).
2. There is option to expand, but no option for rolling article back.
Anyway, if whole body is loaded, and long article is expanded - what is the gain? I believe real excerpt on backend side (like in RSS feed) makes more sense.
If you want to commit anyway, pls fix two issues listed above and create separate file for this template (js_index.html.tmpl seems a good name).

**Comment by mdoff** [comment]
Thanks for replay, I'll fix that issues and move changes to separate file.
You asking what we gain on that change, I think that it will be easier to read and skip long posts that we are not interested.

**Comment by mdoff** [comment]
@rozie I made changes you suggested

**Comment by rozie** [comment]
Thx :-)

**Pull request merged**
